

### register
POST /register HTTP/1.1
Content-Type: application/json
Host: localhost:3000

{
  "email": "daniel2@example.com",
  "password": "Daniel@12345",
  "name": "Daniel2"
}


### login
POST  /login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "email": "daniel2@example.com",
  "password": "Daniel@12345"
}


### Testa rota protegida
POST /protegida HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOnsiaWRWYWx1ZSI6ImE4YTkzOGVjLTcyNjktNDIyMS05OWY2LTA1MWI2NzY0MmYxNiJ9LCJpYXQiOjE3MzA0MzI3MjcsImV4cCI6MTczMDQzNjMyN30.a1IqGMzfy_Qz3RTOnR6CiUgjgQBSwRRPgBSYW5j62w4

{

}
